name: Atualizar Arquivo

on:
  push:
    branches:
      - main  # ou outra branch onde você faz as atualizações

jobs:
  atualizar-arquivo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Baixar Arquivo
      run: |
        wget -O novo-arquivo.csv 'https://onedrive.live.com/download?resid=7275FDA1837FD541%21544&authkey=!AN5y1-y_Lg61BGE&em=2'

    - name: Atualizar GitHub Pages
      run: |
        rm -rf *
        mv novo-arquivo.csv arquivo.csv
        git add arquivo.csv
        git commit -m "Atualizar arquivo CSV"
        git push origin main  # ou outra branch

